version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - 8080:80
    links:
      - fpm
    volumes:
      - ./:/var/www/test/html

  fpm:
    build:
      context: .
      dockerfile: .docker/fpm/Dockerfile
    volumes:
      - ./:/var/www/test/html
    links:
      - db

  db:
    image: mysql:latest
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: api_test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 6080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: qwerty
      PMA_HOST: mysql
